kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
  - git clone https://github.com/dungtri/cups.git .
  - git checkout master

- name: build
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: dungtri/cups
    username:
      from_secret: docker_username
    build_args:
      - arch=arm

  when:
    event:
    - push
    - tag
